---
title: 'STAT6020 : Assignment 10 - Statistical Analysis'
author: "Anamul Haque"
date: "3/22/2020"
output: 
  html_document:
    toc: true
    theme: united
    highlight: tango
---

### Question 1
```{r}
# Declaring the two vectors vec1 and vec2
vec1 <- c(2,1,1,3,2,1,0)
vec2 <- c(3,8,2,2,0,0,0)

# Using vec1 and vec2, I am executing a statement that multiplies the corresponding elements of vec1 & vec2
# If  their sum is greater than 3, the output will be a multiplication for corresponding elements in the of these two vectors
# Otherwise, the code should simply sum the two elements.
# I am using ifelse statement

mult_sum <-ifelse(vec1+vec2>3,
               vec1*vec2,
               vec1+vec2)

# Checking the output
mult_sum
```

### Question 2
```{r}
# Here we are using two functions
## a. diag : Extract or replace the diagonal of a matrix, or construct a diagonal matrix
## b. substr : Extract or replace substrings in a character vector

# MATRIX 1:
############################
# Building the matrix
mymat<-matrix(as.character(1:16),4,4)
mymat1 <- mymat

# Settting a variable from the Matrix 1 which extract the diagnoal elemnts

diag_letter<-substr(diag(mymat),1,1)

# Searching whether there are any g in the diagonal in both upper or lower case and replace it with HERE

replace_g<-ifelse(diag_letter=="G"|diag_letter=="g","HERE",diag(mymat))

# If it finds any g/G at the diagonal, the new matrix 
if(any(replace_g=="HERE")){
  diag(mymat)<-replace_g
  
# Otherwise the entire matrix should be replaced with an identity matrix  
}else{
  mymat<-diag(1,dim(mymat)[1],dim(mymat)[2])
  
}
# Checking MATRIX 1
mymat1_changed <- mymat
mymat1
mymat1_changed


# MATRIX 2:
############################
# Building the matrix
mymat <- matrix(c("DANDELION", "Hycinthus", "Gerbera", "MARIGOLD", "geranium", "ligularia", "Pachysandra", "SNAPDRAGON", "GLADIOLUS"),3,3)

mymat2 <- mymat


# Settting a variable from the Matrix 2 which extract the diagnoal elemnts

diag_letter<-substr(diag(mymat),1,1)

# Searching whether there are any g in the diagonal in both upper or lower case and replace it with HERE

replace_g<-ifelse(diag_letter=="G"|diag_letter=="g","HERE",diag(mymat))

# If it finds any g/G at the diagonal, the new matrix 
if(any(replace_g=="HERE")){
  diag(mymat)<-replace_g
  
# Otherwise the entire matrix should be replaced with an identity matrix  
}else{
  mymat<-diag(1,dim(mymat)[1],dim(mymat)[2])
  
}
# Checking MATRIX 2
mymat2_changed <- mymat
mymat2
mymat2_changed


# MATRIX 3:
############################
# Building the matrix
mymat <- matrix(c("GREAT", "exercises", "right", "here"),2,2,byrow=T)

mymat3 <- mymat


# Settting a variable from the Matrix 2 which extract the diagnoal elemnts

diag_letter<-substr(diag(mymat),1,1)

# Searching whether there are any g in the diagonal in both upper or lower case and replace it with HERE

replace_g<-ifelse(diag_letter=="G"|diag_letter=="g","HERE",diag(mymat))

# If it finds any g/G at the diagonal, the new matrix 
if(any(replace_g=="HERE")){
  diag(mymat)<-replace_g
  
# Otherwise the entire matrix should be replaced with an identity matrix  
}else{
  mymat<-diag(1,dim(mymat)[1],dim(mymat)[2])
  
}
# Checking MATRIX 3
mymat3_changed <- mymat
mymat3
mymat3_changed


```

### Question 3
```{r}
# PART I
############################
# Setting the list
mylist<- list(aa=c(3.4,1),bb=matrix(1:4,2,2), cc=matrix(c(T,T,F,T,F,F),3,2),
              dd="String here",ee=list(c("Hello","you"),matrix(c("hello","there"))),
              ff=matrix(c("red","green","blue","yellow")))

# Here I am using the for loop to count list inside mylist
# Initiating the loop with list count 0
# list_count is the counter
list_count <-0
for(i in 1:length(mylist)){
  member_list<-mylist[[i]]
  # Here I am using nested loop to count if sub member have any list
  if(is.matrix(member_list)==T){
    list_count<-list_count+1
  }else{
    for(j in 1:length(member_list)){
      sub_member_list<-member_list[[j]]
      if(is.matrix(sub_member_list==T)){
        list_count<-list_count+1
      }
    }
  }
}
list_count



# PART II
############################
# Setting the list
mylist <- list("tricked you", as.vector(matrix(1:6, 3,2)))

# Here I am using the for loop to count list inside mylist
# Initiating the loop with list count 0
# list_count is the counter
list_count <-0
for(i in 1:length(mylist)){
  member_list<-mylist[[i]]
  # Here I am using nested loop to count if sub member have any list
  if(is.matrix(member_list)==T){
    list_count<-list_count+1
  }else{
    for(j in 1:length(member_list)){
      sub_member_list<-member_list[[j]]
      if(is.matrix(sub_member_list==T)){
        list_count<-list_count+1
      }
    }
  }
}
list_count




# PART III
############################
# Setting the list
mylist <- list(list(1,2,3),list(c(3,2),2),list(c(1,2),matrix(c(1,2))),rbind(1:10,100:91))

list_count <-0
for(i in 1:length(mylist)){
  member_list<-mylist[[i]]
  # Here I am using nested loop to count if sub member have any list
  if(is.matrix(member_list)==T){
    list_count<-list_count+1
  }else{
    for(j in 1:length(member_list)){
      sub_member_list<-member_list[[j]]
      if(is.matrix(sub_member_list==T)){
        list_count<-list_count+1
      }
    }
  }
}
list_count


```


# Question 4
```{r}
# STRING I
############################
mystring <- "R fever"

index <- 1
ecount <- 0
result <- mystring
while (ecount < 2 && index <= nchar(mystring)) {
  # Using substr to extract a single character of mystring at position 1
  character <- substr(mystring, index, index)
  # Using conditional to check whether the charachter is e/E
  # If so, increase the count by 1
  if (character == "e" || character == "E") {
    ecount <- ecount + 1
  }
  # Checking if the ecount is equak to 2.
  #If so, use substr to set result equal to the characters between 1 and index-1 inclusive
  if (ecount == 2) {
    result <- substr(mystring, 1, index - 1)
  }
  index <- index + 1 #Increment index by 1
}
result


# STRING II
############################
mystring<-"beautiful"

index <- 1
ecount <- 0
result <- mystring
while (ecount < 2 && index <= nchar(mystring)) {
  # Using substr to extract a single character of mystring at position 1
  character <- substr(mystring, index, index)
  # Using conditional to check whether the charachter is e/E
  # If so, increase the count by 1
  if (character == "e" || character == "E") {
    ecount <- ecount + 1
  }
  # Checking if the ecount is equak to 2.
  #If so, use substr to set result equal to the characters between 1 and index-1 inclusive
  if (ecount == 2) {
    result <- substr(mystring, 1, index - 1)
  }
  index <- index + 1 #Increment index by 1
}
result


# STRING III
############################
mystring<-"ECCENTRIC"

index <- 1
ecount <- 0
result <- mystring
while (ecount < 2 && index <= nchar(mystring)) {
  # Using substr to extract a single character of mystring at position 1
  character <- substr(mystring, index, index)
  # Using conditional to check whether the charachter is e/E
  # If so, increase the count by 1
  if (character == "e" || character == "E") {
    ecount <- ecount + 1
  }
  # Checking if the ecount is equak to 2.
  #If so, use substr to set result equal to the characters between 1 and index-1 inclusive
  if (ecount == 2) {
    result <- substr(mystring, 1, index - 1)
  }
  index <- index + 1 #Increment index by 1
}
result



# STRING IV
############################
mystring<-"ElAbOrAte"
index <- 1
ecount <- 0
result <- mystring
while (ecount < 2 && index <= nchar(mystring)) {
  # Using substr to extract a single character of mystring at position 1
  character <- substr(mystring, index, index)
  # Using conditional to check whether the charachter is e/E
  # If so, increase the count by 1
  if (character == "e" || character == "E") {
    ecount <- ecount + 1
  }
  # Checking if the ecount is equak to 2.
  #If so, use substr to set result equal to the characters between 1 and index-1 inclusive
  if (ecount == 2) {
    result <- substr(mystring, 1, index - 1)
  }
  index <- index + 1 #Increment index by 1
}
result


# STRING V
############################
mystring<-"eeeeek!"

index <- 1
ecount <- 0
result <- mystring
while (ecount < 2 && index <= nchar(mystring)) {
  # Using substr to extract a single character of mystring at position 1
  character <- substr(mystring, index, index)
  # Using conditional to check whether the charachter is e/E
  # If so, increase the count by 1
  if (character == "e" || character == "E") {
    ecount <- ecount + 1
  }
  # Checking if the ecount is equak to 2.
  #If so, use substr to set result equal to the characters between 1 and index-1 inclusive
  if (ecount == 2) {
    result <- substr(mystring, 1, index - 1)
  }
  index <- index + 1 #Increment index by 1
}
result
```
